# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from track_msgs/Trk_predRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Trk_predRequest(genpy.Message):
  _md5sum = "1f7d0fe63dcfbf069caa48c6bf650fb4"
  _type = "track_msgs/Trk_predRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 pred_time
"""
  __slots__ = ['pred_time']
  _slot_types = ['float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pred_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Trk_predRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pred_time is None:
        self.pred_time = 0.
    else:
      self.pred_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.pred_time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.pred_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.pred_time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.pred_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from track_msgs/Trk_predResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import track_msgs.msg

class Trk_predResponse(genpy.Message):
  _md5sum = "d920b89b48529f9a775a0efecb5602fd"
  _type = "track_msgs/Trk_predResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Detection_list trk_predicts

================================================================================
MSG: track_msgs/Detection_list
Header header
Detection[] detecs
Information[] infos
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: track_msgs/Detection
geometry_msgs/Vector3 siz
geometry_msgs/Point pos
float32 alp

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: track_msgs/Information
uint8 type
float32 ymin = 0.0
float32 xmin = 0.0
float32 ymax = 0.0
float32 xmax = 0.0
float32 score
float32 orin
"""
  __slots__ = ['trk_predicts']
  _slot_types = ['track_msgs/Detection_list']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trk_predicts

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Trk_predResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.trk_predicts is None:
        self.trk_predicts = track_msgs.msg.Detection_list()
    else:
      self.trk_predicts = track_msgs.msg.Detection_list()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.trk_predicts.header.seq, _x.trk_predicts.header.stamp.secs, _x.trk_predicts.header.stamp.nsecs))
      _x = self.trk_predicts.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.trk_predicts.detecs)
      buff.write(_struct_I.pack(length))
      for val1 in self.trk_predicts.detecs:
        _v1 = val1.siz
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.pos
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.alp
        buff.write(_get_struct_f().pack(_x))
      length = len(self.trk_predicts.infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.trk_predicts.infos:
        _x = val1
        buff.write(_get_struct_B2f().pack(_x.type, _x.score, _x.orin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.trk_predicts is None:
        self.trk_predicts = track_msgs.msg.Detection_list()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.trk_predicts.header.seq, _x.trk_predicts.header.stamp.secs, _x.trk_predicts.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trk_predicts.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trk_predicts.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trk_predicts.detecs = []
      for i in range(0, length):
        val1 = track_msgs.msg.Detection()
        _v3 = val1.siz
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.pos
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.alp,) = _get_struct_f().unpack(str[start:end])
        self.trk_predicts.detecs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trk_predicts.infos = []
      for i in range(0, length):
        val1 = track_msgs.msg.Information()
        _x = val1
        start = end
        end += 9
        (_x.type, _x.score, _x.orin,) = _get_struct_B2f().unpack(str[start:end])
        self.trk_predicts.infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.trk_predicts.header.seq, _x.trk_predicts.header.stamp.secs, _x.trk_predicts.header.stamp.nsecs))
      _x = self.trk_predicts.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.trk_predicts.detecs)
      buff.write(_struct_I.pack(length))
      for val1 in self.trk_predicts.detecs:
        _v5 = val1.siz
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.pos
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.alp
        buff.write(_get_struct_f().pack(_x))
      length = len(self.trk_predicts.infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.trk_predicts.infos:
        _x = val1
        buff.write(_get_struct_B2f().pack(_x.type, _x.score, _x.orin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.trk_predicts is None:
        self.trk_predicts = track_msgs.msg.Detection_list()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.trk_predicts.header.seq, _x.trk_predicts.header.stamp.secs, _x.trk_predicts.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trk_predicts.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trk_predicts.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trk_predicts.detecs = []
      for i in range(0, length):
        val1 = track_msgs.msg.Detection()
        _v7 = val1.siz
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.pos
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.alp,) = _get_struct_f().unpack(str[start:end])
        self.trk_predicts.detecs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trk_predicts.infos = []
      for i in range(0, length):
        val1 = track_msgs.msg.Information()
        _x = val1
        start = end
        end += 9
        (_x.type, _x.score, _x.orin,) = _get_struct_B2f().unpack(str[start:end])
        self.trk_predicts.infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
class Trk_pred(object):
  _type          = 'track_msgs/Trk_pred'
  _md5sum = '3dc63b2f99da79eb20c7b6a1c64058a7'
  _request_class  = Trk_predRequest
  _response_class = Trk_predResponse
